FROM edgedb/edgedb

ENV EDGEDB_SERVER_SECURITY=insecure_dev_mode
ENV EDGEDB_SERVER_ADMIN_UI=enabled
# ENV EDGEDB_SERVER_TLS_CERT_MODE=generate_self_signed
# ENV EDGEDB_SERVER_BIND_ADDRESS=0.0.0.0

ENV EDGEDB_SERVER_BACKEND_DSN_ENV=${DATABASE_URL}
ENV EDGEDB_SERVER_PORT_ENV=${PORT}
